export 'payment/paymen_screen.dart';
export 'withdraw_money/withdraw_screen.dart';
export 'splash/splash_screen.dart';
export 'test_page.dart';
export 'login/login_screen.dart';
export 'register/sign_up_screen.dart';
export 'profile/profile_screen.dart';
export 'home/body_home_screen.dart';
export 'contact/contact_screen.dart';